
package co.com.cetus.cetuscontrol.ejb.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CetusControlService", targetNamespace = "http://service.ejb.cetuscontrol.cetus.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CetusControlService {


    /**
     * 
     * @param reloadParameterRequestDTO
     * @return
     *     returns co.com.cetus.cetuscontrol.ejb.service.ResponseWSDTO
     */
    @WebMethod
    @WebResult(name = "responseWSDTO", targetNamespace = "")
    @RequestWrapper(localName = "reloadParameter", targetNamespace = "http://service.ejb.cetuscontrol.cetus.com.co/", className = "co.com.cetus.cetuscontrol.ejb.service.ReloadParameter")
    @ResponseWrapper(localName = "reloadParameterResponse", targetNamespace = "http://service.ejb.cetuscontrol.cetus.com.co/", className = "co.com.cetus.cetuscontrol.ejb.service.ReloadParameterResponse")
    public ResponseWSDTO reloadParameter(
        @WebParam(name = "reloadParameterRequestDTO", targetNamespace = "")
        ReloadParameterRequestDTO reloadParameterRequestDTO);

}
